### ISSUE TITLE
entrevista

### ISSUE THREAD

**Issue by christopheremv** [SistemasTecTlaxiaco/actividad-2-entrevista-dream-team1#2]
[entrevista gestion de proyectos.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2-entrevista-dream-team1/files/9472658/entrevista.gestion.de.proyectos.pdf)

**Comment by Rmz-Rigo** [comment]
CALIFICACION: 20/20

**Comment by josealfredo79** [comment]
Al final de la entrevista debe haber una sintesis

**Comment by josealfredo79** [comment]
Quien evaluo debe realizarlo correctamente @Rigoberto2001

**Comment by josealfredo79** [comment]
Bien hecho
